# Application
spring.application.name=collection-svc
server.port=8083

# PostgreSQL
spring.datasource.url=jdbc:postgresql://collection-db:5432/collection_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Services
# Services - Utilise l'IP de la passerelle Docker
services.media-svc.url=http://172.17.0.1:8082
services.auth-svc.url=http://172.17.0.1:8081

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=com.collection.controller

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# Logs
logging.level.com.collection=DEBUG
logging.level.org.hibernate.SQL=DEBUG