services:
  postgres-db:
    image: postgres:17-alpine
    container_name: auth-db-container
    environment:
      - POSTGRES_DB=mediatheque_auth
      - POSTGRES_USER=user_admin
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_admin -d mediatheque_auth"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-svc
    container_name: auth-service-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/mediatheque_auth
      - SPRING_DATASOURCE_USERNAME=user_admin
      - SPRING_DATASOURCE_PASSWORD=password123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - JWT_EXPIRATION=86400000
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=ton-email@gmail.com
      - SPRING_MAIL_PASSWORD=ton-mot-de-passe-application-google
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - APP_FRONTEND_URL=http://localhost:4200
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres_auth_data: