#  Server
server.port=8082

# Application
spring.application.name=media-svc
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/mediatheque
spring.datasource.username=postgres
spring.datasource.password=1234
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
# Flyway
spring.flyway.enabled=false

springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
logging.level.org.springframework.web.client=DEBUG
logging.level.com.mediatheque=DEBUG

# FILMS & SÉRIES

# TVMaze ? sans clé
external.tvmaze.base-url=https://api.tvmaze.com

# YouTube Data API v3
external.youtube.base-url=https://www.googleapis.com/youtube/v3
external.youtube.api-key=AIzaSyB_f_UvBd4cxWDLJLqHWV_bY9Owx9ELJTk

# Internet Archive ? sans clé (films)
external.archive.base-url=https://archive.org

# Watchmode
external.watchmode.base-url=https://api.watchmode.com/v1
external.watchmode.api-key=FWhrH4WQeGJm9dNneZTeB8gT78ZhOjDzyilHAw0f


# PodcastIndex (auth HMAC SHA-1)
external.podcastindex.base-url=https://api.podcastindex.org/api/1.0
external.podcastindex.api-key=WDMGGBCVV5SANPEPUC6W
external.podcastindex.api-secret=DXceGN24vNf4f7CErXzP9s7rKsXHvsKF44kDLpe3

# iTunes Search ? sans clé (fallback)
external.itunes.base-url=https://itunes.apple.com

# JEUX VIDÉO

# RAWG ? grande base de données jeux
external.rawg.base-url=https://api.rawg.io/api
external.rawg.api-key=c8159cd8a83b4c59a11fdc4e06447408

# FreeToGame ? jeux F2P, sans clé
external.freetogame.base-url=https://www.freetogame.com/api

# API League
external.apileague.base-url=https://api.apileague.com
external.apileague.api-key=4e8ea0429aac45a888e5c6106785027b

# LIVRES

# Internet Archive ? sans clé (livres domaine public)
external.internetarchive.base-url=https://archive.org

# OpenLibrary ? sans clé
external.openlibrary.base-url=https://openlibrary.org

# BigBook API
external.bigbook.base-url=https://api.bigbookapi.com
external.bigbook.api-key=4e8ea0429aac45a888e5c6106785027b

# Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
file.upload-dir=./uploads